version: "3"

services:
  database:
    container_name: app_mysql
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: pa55w0rd
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: db_test
    ports: 
      - "3306:3306"
    restart: always
    networks:
      - overlay
  app:
    container_name: app
    restart: always
    build:
      context: ./worker
      dockerfile: ../Dockerfile
    working_dir: /home/app
    volumes:
      - ./worker:/home/app
    ports:
      - "8088:8088"
    command: "sh mvnw clean spring-boot:run"
    depends_on:
      - database
    networks:
      - overlay
networks:
  overlay: