spring:
  profiles:
    active: ${spring.profiles.active}

logging:
    level:
      TAlarmInformationMapper: debug

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.ipenta.entity
  mapper-locations: classpath:mapper/*.xml
